### ISSUE TITLE
Error while trying to generate IsoSurface or Compute Forces from FreeCAD

### ISSUE THREAD

**Issue by ShreyanshDarshan** [DualSPHysics/DualSPHysics#60] opened 2020-08-22 17:45 UTC
After the simulation is complete, when I click on the IsoSurface button in the post processing tab, the following error gets generated:

```
IsoSurface v5.0.122 (09-07-2020)
=================================
LoadDsphConfig> .../bin/windows/DsphConfig.xml

* Exception (JIsoSurfaceCfgRun::ErrorParm) at ..\Source\JCfgRunBase.cpp:128
Text: Parameter "" unrecognised or invalid. (Level cfg:0, Parameter:4)


* 
* Exception (JIsoSurfaceCfgRun::ErrorParm) at ..\Source\JCfgRunBase.cpp:128
Text: Parameter "" unrecognised or invalid. (Level cfg:0, Parameter:4)
```

The same error crops up even when I try to Compute Forces. Any help is really appreciated.

**Comment by zlotny** [comment] 2020-08-24 08:30
Hi there, that's probably an error with DesignSPHyiscs, rather than DualSPHyiscs. It seems a duplicate of:

https://github.com/DualSPHysics/DesignSPHysics/issues/82

Can you please attach a zip file with your case folder? I can't tell by the error which parameter is being written incorrectly so I can't find where to fix it.

**Comment by zlotny** [comment] 2020-08-26 10:00
The errror should now be fixed on the latest version. Please update DesignSPHyiscs. If you keep having issues with it please open the issues that arise using the command line on [the DesignSPHysics repository](https://github.com/DualSPHysics/DesignSPHysics/)

**Closed by zlotny** 2020-08-26 10:00 UTC
